name: kodi_script
description: A lightweight, embeddable scripting language for Dart applications.
version: 0.2.0
homepage: https://github.com/issadicko/kodi-script-dart
repository: https://github.com/issadicko/kodi-script-dart
issue_tracker: https://github.com/issadicko/kodi-script-dart/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  crypto: ^3.0.3

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
